### ISSUE TITLE
The dockerhub page for this project requires to log in

### ISSUE THREAD

**Issue by SerinitySW** [erdnaxeli/castblock#1]
This project seems pretty fantastic! I'd love to run it on my unRAID server 24/7, but I can't find it on DockerHub. Is there plans to do so?

**Comment by erdnaxeli** [comment]
Thanks :)

You can find it here: https://hub.docker.com/repository/docker/erdnaxeli/castblock.

**Comment by erdnaxeli** [comment]
I just noticed that maybe you are talking about an ARM server. If so `erdnaxeli/castblock:latest` now support `linux/arm` too.

**Comment by SerinitySW** [comment]
Actually, I'm on x86, but that's awesome for if I ever want to throw it on a Pi!

I did notice something weird though, I have to login to DockerHub in order to view the repo - which makes it inaccessible on unRAID. Any way to make it public-facing?

**Comment by erdnaxeli** [comment]
That's weird, the repo should be public. Did you actually try to do a docker pull ?

**Comment by SerinitySW** [comment]
Docker pull works, but docker pull isn't 'supported' on unraid. I agree it's weird, I'm required to sign-in to access the dockerhub page. Can you replicate the same by logging out?

**Comment by erdnaxeli** [comment]
Glad to read you managed to pull the container :)

But indeed something is weird. I logged out, then when to the castblock and it redirected me to the login page. I retried (without login), and it worked… Second thing, the image is not visible through search: https://hub.docker.com/search?q=castblock&type=image. But my two other uploaded images are.

**Comment by ToasterDEV** [comment]
> I just noticed that maybe you are talking about an ARM server. If so `erdnaxeli/castblock:latest` now support `linux/arm` too.

Hey there, while on the topic of Raspberry Pi support, would it be an option to add support for arm64 please?

**Comment by erdnaxeli** [comment]
@ToasterDEV I created a new issue for that :)

About dockerhub, I finally understood. In my previous comment (it is now edited) I posted a bad link:
* correct link: https://hub.docker.com/r/erdnaxeli/castblock
* incorrect link, required login: https://hub.docker.com/repository/docker/erdnaxeli/castblock/

Btw the project now correctly shows up in the search.
