### ISSUE TITLE
Question about seekto offset

### ISSUE THREAD

**Issue by stephen304** [erdnaxeli/castblock#10]
I noticed that there's a 1 second offset to the seek-to command. As far as I can tell the seeking is really accurate and removing the 1 second offset results in better aligned skipping so you don't get the last word of the sponsor read. What would you think of removing that offset? (As long as it doesn't cause #9 )

**Comment by erdnaxeli** [comment]
Yeah, when I was testing it at the begining it felt like it was skiping a bit of the real video, that's why I added this offset. But you're right, I should remove it.

I will make it configurable, with no offset as default.

**Comment by erdnaxeli** [comment]
Fixed in 47fd3862e8aaf68c95ffc604c24bcd7723f12baf
