### ISSUE TITLE
castblock runs in foreground with given command in readme

### ISSUE THREAD

**Issue by sniperwhg** [erdnaxeli/castblock#22]
Adding a -d to run in detach mode as shown below seems to allow docker to just run the castblock properly without the terminal eating all additional inputs.

`docker run --rm -d --network host erdnaxeli/castblock`

**Comment by erdnaxeli** [comment]
Yes :)

I will clarify the README.

**Comment by erdnaxeli** [comment]
Fixed in c90a9cae1a158cd13d774b837b757b77d8a04bae.
