### ISSUE TITLE
[FEATURE] Termux Support

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [erdnaxeli/castblock#43]
Is there any way to run castblock? I feel like more often than not, chromecast is used because the user doesn't want to watch on a small screen, therefor, most chromecast users only have phones and not computers.

[Termux](https://termux.com/) is an Android terminal emulator and Linux environment app that works directly with no rooting or setup required. A minimal base system is installed automatically - additional packages are available using the APT package manager.

Is there any way to run castblock on termux?

**Comment by erdnaxeli** [comment]
I don't think there is an easy way to run it on termux so far, as Crystal is [not yet supported](https://github.com/termux/termux-packages/issues/3401).

**Comment by ItsIgnacioPortal** [comment]
Interesting.. How about making releases here on Github with pre-compiled binaries? [Crystal has a page about Cross-compilation](https://crystal-lang.org/reference/1.4/syntax_and_semantics/cross-compilation.html)

**Comment by erdnaxeli** [comment]
I already do some cross compilation to build the docker images for raspberry pi, I could try to do the same for android plateforms.

**Comment by erdnaxeli** [comment]
Yes, that is what I meant :)

**Comment by ItsIgnacioPortal** [comment]
Update on cross compilation: I tried to cross compile for "aarch64-unknown-linux-android24", but it fails with:
```
Showing last frame. Use --error-trace for full trace.

In /usr/share/crystal/src/exception/call_stack/libunwind.cr:1:1

 1 | require "c/dlfcn"
     ^
Error: can't find file 'c/dlfcn'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?
```

I ran `shards install` but the issue didn't go away. I think the only solution is to follow the steps described here https://forum.crystal-lang.org/t/running-crystal-on-termux/3880/6 and compile this from termux directly

**Comment by ItsIgnacioPortal** [comment]
I've spent an unreasonable amount of time trying to get Crystal to work on termux. Screw crystal. I'm switching to another project https://github.com/nichobi/sponsorblockcast
