### ISSUE TITLE
Auto-skip skippable ads

### ISSUE THREAD

**Issue by Kevga** [erdnaxeli/castblock#45]
The --mute-ads feature makes native ads more bearable, but you still have to grab and unlock your phone to skip those 2+ minute ads. Can this be automated as well?

Edit: Oops, I did check issues before opening this, but I only now saw the open PR.

**Comment by RemcoSchrijver** [comment]
Last activity on #39 is from 6 months ago so I think this issue is not unwarranted.

**Comment by erdnaxeli** [comment]
The PR was finally merged, the docker images will follow :)
