### ISSUE TITLE
Castblock claims to be skipping, but nothing happens

### ISSUE THREAD

**Issue by stephen304** [erdnaxeli/castblock#5]
Ran into this just now - It looks like it's trying to skip the same segment but nothing actually happened:

```
Apr 28 11:46:20 pihole castblock[76792]: 2021-04-28T15:46:20.632400Z   INFO - castblock.blocker: Found a sponsor segment, skipping it. -- id: "kMxcw_lQBjI", start: 40.812607, end: 102.831894
Apr 28 11:46:33 pihole castblock[76792]: 2021-04-28T15:46:33.636287Z   INFO - castblock.blocker: Found a sponsor segment, skipping it. -- id: "kMxcw_lQBjI", start: 40.812607, end: 102.831894
Apr 28 11:46:43 pihole castblock[76792]: 2021-04-28T15:46:43.642162Z   INFO - castblock.blocker: Found a sponsor segment, skipping it. -- id: "kMxcw_lQBjI", start: 40.812607, end: 102.831894
Apr 28 11:46:53 pihole castblock[76792]: 2021-04-28T15:46:53.648376Z   INFO - castblock.blocker: Found a sponsor segment, skipping it. -- id: "kMxcw_lQBjI", start: 40.812607, end: 102.831894
Apr 28 11:47:06 pihole castblock[76792]: 2021-04-28T15:47:06.650518Z   INFO - castblock.blocker: Found a sponsor segment, skipping it. -- id: "kMxcw_lQBjI", start: 40.812607, end: 102.831894
Apr 28 11:47:16 pihole castblock[76792]: 2021-04-28T15:47:16.652738Z   INFO - castblock.blocker: Found a sponsor segment, skipping it. -- id: "kMxcw_lQBjI", start: 40.812607, end: 102.831894
Apr 28 11:47:26 pihole castblock[76792]: 2021-04-28T15:47:26.657088Z   INFO - castblock.blocker: Found a sponsor segment, skipping it. -- id: "kMxcw_lQBjI", start: 40.812607, end: 102.831894
Apr 28 11:47:39 pihole castblock[76792]: 2021-04-28T15:47:39.662750Z   INFO - castblock.blocker: Found a sponsor segment, skipping it. -- id: "kMxcw_lQBjI", start: 40.812607, end: 102.831894
Apr 28 11:47:49 pihole castblock[76792]: 2021-04-28T15:47:49.664129Z   INFO - castblock.blocker: Found a sponsor segment, skipping it. -- id: "kMxcw_lQBjI", start: 40.812607, end: 102.831894
Apr 28 11:47:59 pihole castblock[76792]: 2021-04-28T15:47:59.666159Z   INFO - castblock.blocker: Found a sponsor segment, skipping it. -- id: "kMxcw_lQBjI", start: 40.812607, end: 102.831894

```

Unfortunately I wasn't running in debug mode. Also worth noting that it seems to be permanently stuck in this state.

I'm not familiar at all with the go-chromecast http api, any ideas on what might be the cause?

Edit: Could it be that the watch thread is still connected but the http api used for skipping lost the device?

**Comment by erdnaxeli** [comment]
The log for error when calling `/seek-to` uses debug level :roll_eyes: . I changed it to error level and I added the error from go-chromecast in the message. You can use master (or latest docker images), if it happens again we will see the error.

Anyway the timing is weird. `watch` is set to send a message every second, and the code just react to those messages, but thoses log indicate that it is trying to seek every 10 or 13s. It seems like something (the httpserver probably) is either slow to timeout or does automatic retries.

**Comment by erdnaxeli** [comment]
I just add the same bug as you!

This is what I saw:
* `/devices` still see the device
* `/connect?uuid=...` says the device is already connected
* but `/seek-to` complains with "unable to seek-to device: unable to write binary format: write tcp 192.168.1.42:58146->192.168.1.36:8009: write: broken pipe"

Unfortunately I didn't try to call `/disconnect`, then `/connect` again, then `/seek-to`. If you do have the error again could you try to do that please?

**Comment by erdnaxeli** [comment]
The error comes from here: https://github.com/vishen/go-chromecast/blob/0795e28217f8b18586ebb69c1569c46451dbab0b/cast/connection.go#L121. It seems like the connection is just broken. I will implement a disconnect / reconnect mechanism.

**Comment by stephen304** [comment]
Sounds good, I was too slow to reproduce the issue :)

**Comment by stephen304** [comment]
Got it to happen again, this is what happens when I try to disconnect / reconnect:
![image](https://user-images.githubusercontent.com/981915/116720098-cf743a00-a9a9-11eb-9071-dec9d764a645.png)
It still doesn't seem to fix the issue

**Comment by erdnaxeli** [comment]
Yes, go-chromecast can't disconnect from a broken connection. I am opening an issue on their side.

**Comment by stephen304** [comment]
Looks like that fix makes disconnecting and reconnecting work to fix the issue. I guess all that's needed is to auto reconnect when it gets disconnected

**Comment by erdnaxeli** [comment]
Tell me if it happens again. I spotted a weird bug in go-chromecast where the /seek-to endpoint can return a 200 even if the connection is broken (https://github.com/vishen/go-chromecast/issues/106). If that happens we will not do a disconnect / reconnect.

But I suspect that in real life conditions the endpoint would return an error, and in that case the code will try to reconnect.
