### ISSUE TITLE
SponsorBlock Server Address

### ISSUE THREAD

**Issue by goldbattle** [erdnaxeli/castblock#50]
It would be nice to be able to change the server address to a self-hosted / mirror.
This as an environment variables `SPONSER_SERVER` or something would be great.
Also being able to disable the tls would be good too to fully complete the feature (or infer this from the http / https?).
https://github.com/erdnaxeli/castblock/blob/91cfcd3eefbccf778df148719376d76d4230a5db/src/sponsorblock.cr#L23

**Comment by erdnaxeli** [comment]
Good suggestion, this should be easy to implement.
