### ISSUE TITLE
Docker image for arm64

### ISSUE THREAD

**Issue by erdnaxeli** [erdnaxeli/castblock#6]
> I just noticed that maybe you are talking about an ARM server. If so `erdnaxeli/castblock:latest` now support `linux/arm` too.

Hey there, while on the topic of Raspberry Pi support, would it be an option to add support for arm64 please?

_Originally posted by @ToasterDEV in https://github.com/erdnaxeli/castblock/issues/1#issuecomment-829113113_

**Comment by erdnaxeli** [comment]
@toasterDEV the current arm image does not work on arm64?

**Comment by ToasterDEV** [comment]
At the moment it seems to be having issues while trying to first deploy the container.

Running `docker run hello-world` works as intended, as does deploying Home Assistant or BubbleUPNP server, but for some reason running `docker run --network=host erdnaxeli/castblock` leads to
```
 docker run --network=host erdnaxeli/castblock: No such file or directory
```
I've already tried deploying from the digest hash and rebooting, but to no avail at the moment. Perhaps it's an issue with my particular setup, but I'm not sure where could I begin to troubleshoot given so far this has been the only image I've had issues with.

**Comment by erdnaxeli** [comment]
> No such file or directory

You're right, that looks like a problem with the architecture. You may look at how to run 32 bits binaries on your system, but I am also trying to build a 64 bits docker image.

**Comment by erdnaxeli** [comment]
@ToasterDEV could you try the `erdnaxeli/castblock:aarch64` image? It should work with your arm64 server.

**Comment by ToasterDEV** [comment]
> @ToasterDEV could you try the `erdnaxeli/castblock:aarch64` image? It should work with your arm64 server.

Deploying the image after pulling from the aarch64 branch by running 'docker run --network="host" f78679a27784' proved successful.

For debugging purposes the output of the host's uname is:
'''
Linux RaspberryPi4 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux
'''

**Comment by erdnaxeli** [comment]
Cool!
